create table if not exists room_blocks (
  id bigint generated by default as identity primary key,
  room_id uuid not null references rooms(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists room_blocks_room_id_idx on room_blocks(room_id);
create index if not exists room_blocks_date_idx on room_blocks(start_date, end_date);
